# Generated by Django 3.0.6 on 2020-05-28 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название выпечки')),
                ('image', models.ImageField(upload_to='bakerser/', verbose_name='Фото выпечки')),
                ('composition', models.TextField(verbose_name='Состав выпечки')),
                ('description', models.TextField(verbose_name='Описание выпечки')),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания выпечки')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Выпечку',
                'verbose_name_plural': 'Выпечка',
            },
        ),
        migrations.CreateModel(
            name='MakeAnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=32, verbose_name='Имя заказчика')),
                ('email_customer', models.EmailField(max_length=64, verbose_name='Email заказчика')),
                ('number_customer', models.CharField(max_length=32, verbose_name='Номер телефона заказчика')),
                ('order', models.TextField(max_length=1024, verbose_name='Сам заказ')),
                ('location', models.CharField(max_length=256, verbose_name='Место для доставки заказа')),
                ('date_order', models.DateTimeField(default=datetime.date.today, verbose_name='Дата заказа')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значиние')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звёзды рейтинга',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='bakerall.Food', verbose_name='фильм')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakerall.RatingStar', verbose_name='звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('author', models.CharField(max_length=64, verbose_name='Имя комментатора')),
                ('comment_text', models.CharField(max_length=256, verbose_name='Текст комментария')),
                ('food', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bakerall.Food', verbose_name='выпечка')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='bakerall.Comment', verbose_name='родитель')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
